# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/segfolt/repos/hackassembler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/segfolt/repos/hackassembler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/segfolt/repos/hackassembler/CMakeFiles /home/segfolt/repos/hackassembler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/segfolt/repos/hackassembler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HackAssembler

# Build rule for target.
HackAssembler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HackAssembler
.PHONY : HackAssembler

# fast build rule for target.
HackAssembler/fast:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/build
.PHONY : HackAssembler/fast

src/hackAssembler/assembler.o: src/hackAssembler/assembler.cc.o

.PHONY : src/hackAssembler/assembler.o

# target to build an object file
src/hackAssembler/assembler.cc.o:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/hackAssembler/assembler.cc.o
.PHONY : src/hackAssembler/assembler.cc.o

src/hackAssembler/assembler.i: src/hackAssembler/assembler.cc.i

.PHONY : src/hackAssembler/assembler.i

# target to preprocess a source file
src/hackAssembler/assembler.cc.i:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/hackAssembler/assembler.cc.i
.PHONY : src/hackAssembler/assembler.cc.i

src/hackAssembler/assembler.s: src/hackAssembler/assembler.cc.s

.PHONY : src/hackAssembler/assembler.s

# target to generate assembly for a file
src/hackAssembler/assembler.cc.s:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/hackAssembler/assembler.cc.s
.PHONY : src/hackAssembler/assembler.cc.s

src/hackAssembler/preprocess.o: src/hackAssembler/preprocess.cc.o

.PHONY : src/hackAssembler/preprocess.o

# target to build an object file
src/hackAssembler/preprocess.cc.o:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/hackAssembler/preprocess.cc.o
.PHONY : src/hackAssembler/preprocess.cc.o

src/hackAssembler/preprocess.i: src/hackAssembler/preprocess.cc.i

.PHONY : src/hackAssembler/preprocess.i

# target to preprocess a source file
src/hackAssembler/preprocess.cc.i:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/hackAssembler/preprocess.cc.i
.PHONY : src/hackAssembler/preprocess.cc.i

src/hackAssembler/preprocess.s: src/hackAssembler/preprocess.cc.s

.PHONY : src/hackAssembler/preprocess.s

# target to generate assembly for a file
src/hackAssembler/preprocess.cc.s:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/hackAssembler/preprocess.cc.s
.PHONY : src/hackAssembler/preprocess.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/misc/symbolTable.o: src/misc/symbolTable.cc.o

.PHONY : src/misc/symbolTable.o

# target to build an object file
src/misc/symbolTable.cc.o:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/misc/symbolTable.cc.o
.PHONY : src/misc/symbolTable.cc.o

src/misc/symbolTable.i: src/misc/symbolTable.cc.i

.PHONY : src/misc/symbolTable.i

# target to preprocess a source file
src/misc/symbolTable.cc.i:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/misc/symbolTable.cc.i
.PHONY : src/misc/symbolTable.cc.i

src/misc/symbolTable.s: src/misc/symbolTable.cc.s

.PHONY : src/misc/symbolTable.s

# target to generate assembly for a file
src/misc/symbolTable.cc.s:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/misc/symbolTable.cc.s
.PHONY : src/misc/symbolTable.cc.s

src/misc/util.o: src/misc/util.cc.o

.PHONY : src/misc/util.o

# target to build an object file
src/misc/util.cc.o:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/misc/util.cc.o
.PHONY : src/misc/util.cc.o

src/misc/util.i: src/misc/util.cc.i

.PHONY : src/misc/util.i

# target to preprocess a source file
src/misc/util.cc.i:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/misc/util.cc.i
.PHONY : src/misc/util.cc.i

src/misc/util.s: src/misc/util.cc.s

.PHONY : src/misc/util.s

# target to generate assembly for a file
src/misc/util.cc.s:
	$(MAKE) -f CMakeFiles/HackAssembler.dir/build.make CMakeFiles/HackAssembler.dir/src/misc/util.cc.s
.PHONY : src/misc/util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... HackAssembler"
	@echo "... src/hackAssembler/assembler.o"
	@echo "... src/hackAssembler/assembler.i"
	@echo "... src/hackAssembler/assembler.s"
	@echo "... src/hackAssembler/preprocess.o"
	@echo "... src/hackAssembler/preprocess.i"
	@echo "... src/hackAssembler/preprocess.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/misc/symbolTable.o"
	@echo "... src/misc/symbolTable.i"
	@echo "... src/misc/symbolTable.s"
	@echo "... src/misc/util.o"
	@echo "... src/misc/util.i"
	@echo "... src/misc/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

